
export const ROUTES = {
	AUTH: {
		LOGIN: 'login',
		REGISTER: 'registerCustomer',
		LOGOUT: 'logout',
		REGISTERREQUEST: 'registerPublisher',
		REGISTERADMIN: 'registerAdmin',
		UPDATEPROFILEPHOTO: 'profilePhoto',
		ONESIGNAL_UPDATE_PLAYERID:'onesignalUpdatePlayerId',
		GET_PREFERENCES:'getPreferences',
		SET_PREFERENCES:'setPreferences',
		SET_PHOTO_THEME:'setPhotoTheme',
		DELETE_PREFERENCES:'deletePreferences',
		SEND_VERIFICATION_MAIL:'sendVerificationMail',
		GET_USER_INFO:'getUserInfo',
		CHECK_EMAIL_VERIFIED:"checkEmailVerified"
	},
	ADMIN: {
		GETPUBLISHER: 'getpublisher',
		GETINACTIVEPUBLISHER: 'getinactivationpublishers',
		GETACTIVEPUBLISHER:'getActivePublishers',
		ACTIVATEPUBLISHER: 'activateFullPublisher', // attiva e disattiva
		GETPUBLISHERBYNAME: 'getpublisherbyname',
		DELETEREQUEST: 'deleteregistration',
		GETMARKS:'getMarks',
		BANUSER:'manageUserBan',
		GETTHUNDERLIST:'getThunderdealsList',
		SAVETHUNDERDEAL:'saveThunderdeal',
		DEACTIVATETHUNDERDEAL:'deactivateThunderdeal',
		EDITTHUNDERDEAL:'editThunderdeal',
		GETTHUNDERBYID:'getThunderDetail',
		GETNOTIFICATIONLIST:'getNotificationList',
		MARKASREAD:'markAsRead',
		MARKSALLREAD:'markAllAsRead'
	},
	PUBLISHER: {
		GETADSBYPUBLISHERID: 'getAdsByPublisherId',
		GETFEEDBACK: 'getPublisherFeedback',
		GETPROFILE: 'getProfile',
		GETADSBYID: 'getAdById',
		INSERTADS: 'insertads',
		EDITADS: 'editAds',
		UPLOADPHOTO: 'uploadPhoto',
		DELETEPHOTO: 'deletePhoto',
		DELETEADSBYID: 'deleteadbyid',
		CHANGEREQUESTSTATUS: 'changeRequestStatus',
		GETREQUESTS: 'getRequests',
		GETPRODUCTS:'getProducts',
		EDITCONTACT:'editContact',
		GETREQUESTDETAIL: 'getRequestDetail',
		GETREQUESTHISTORY:'getRequestsHistory',
		GETREQUESTDETAILSHISTORY:'getRequestDetailsHistory',
		GETAPPOINTMENTS:'getAppointments',
		GETPUBLISHERFEEDBACK:'getPublisherFeedback',
		GETPUBLISHERFEEDBACKLIST:'getPublisherFeedbackList',
		GETPUBLISHERCOUNTFOLLOW:'getCountFollow',
		GETACTIVETHUNDER:'getActiveThunderDealsList',
		GETTHUNDERBYID:'getThunderDealById',
		GETTHUNDERDEALPRODUCTSLIST:'getThunderDealProductsList',
		INSERTTHUNDERDEALPRODUCTOFFER:'insertThunderDealOfferOnProduct',
		EDITTHUNDERDEALPRODUCTOFFER:'editThunderDealOfferOnProduct',
		GETNOTIFICATIONLIST:'getNotificationList',
		MARKASREAD:'markAsRead',
		MARKSALLREAD:'markAllAsRead',
		INSERTNOTIFICATION:'insertNotification',
		GETPRODUCTDETAILS:'getProductDetails',
		GETPRODUCTFEEDBACKLIST:'getProductFeedbackList',
		GETPRODUCTFEEDBACK:'getProductFeedback',
		GETINFOBOX:'getInfoBox'
},
	PUBLIC: {
		SEARCHPUBLISHERBYCATEGORYID: 'searchpublisherbycategoryid',
		STORECATEGORIES: 'storecategories',
		SEARCHPRODUCTS: 'searchproducts',
	},
	CUSTOMER: {
		DELETEITEMFROMREQUEST: 'deleteItemFromRequest',
		ADDITEMTOREQUEST: 'addItemToRequest',
		GETPROFILE: 'getProfile',
		GETREQUESTS: 'getRequests',
		GETREQUESTDETAIL: 'getRequestDetail',
        GETPUBLISHERPROFILE: 'getPublisherProfile',
		GETPRODUCTBYPUBLISHER:'getProductsByPublisher',
		EDITCONTACT:'editContact',
		ADDCONTACT:'addContact',
		GETPUBLISHERPRODUCTSEARCH:'getPublisherProductSearch',
		GETREQUESTSENT:'getRequestSent',
		SENDREQUEST:'sendRequestToPublisher',
		GETREQUESTSENTPENDING:'getRequestPending',
		GETREQUESTHISTORY:'getRequestsHistory',
		GETREQUESTDETAILSHISTORY:'getRequestDetailsHistory',
		SAVEPRODUCTFEEDBACK:'saveProductFeedback',
		PROPOSEAPPOINTMENT:'proposeAppointment',
		MARKPUBLISHER:'markPublisher',
		EDITAPPONTMENT:'editAppointment',
		GETPRODUCTFEEDBACK:'getProductFeedback',
		GETPRODUCTDETAILS:'getProductDetails',
		CANPROPOSE:'canPropose',
		SAVEPUBLISHERFEEDBACK:'savePublisherFeedback',
		GETPUBLISHERFEEDBACK:'getPublisherFeedback',
		GETPUBLISHERFEEDBACKLIST:'getPublisherFeedbackList',
		GETDISCOUNTPRODUCTS:'getDiscountedProducts',
		HASVOTED:'hasVoted',
		GETPRODUCTFEEDBACKLIST:'getProductFeedbackList',
		FOLLOWPUBLISHER:'followPublisher',
		UNFOLLOWPUBISHER:'unFollowPublisher',
		FAVORUTITEPRODUCT:'favouriteProduct',
		UNFAVOURITEPRODUCT:'unFavouriteProduct',
		GETCOUNTFOLLOWERPUBLISHER:'getCountFollowForPublisher',
		GETHASFOLLOW:'getHasFollow',
		GETLISTFAVOURITEPRODUCT:'getListOfFavouriteProducts',
		GETFAVOURITEPRODUCT:'getFavouriteProduct',
		GETACTIVETHUNDER:'getActiveThunderDealsList',
		GETTHUNDERDEALPRODUCTSLIST:'getThunderDealProductsList',
		GETNOTIFICATIONLIST:'getNotificationList',
		MARKASREAD:'markAsRead',
		MARKSALLREAD:'markAllAsRead',
		INSERTNOTIFICATION:'insertNotification',
		GETFOLLOWED:'getFollowed',
		SEARCHPUBLISHER:'getpublisherbyname',
		ADDSHIPPINGADDRESTOREQ:'addShippingAddressToRequest',
		GETREQUESTCOUNTPENDING:'getRequestCountPending',
		GET_PUBLISHERS:'getPublishers'
	},
    TERMS:'getprivacyandterms'
};
