export enum NotificationTypeEnum {
    

    /*
    REQUEST_ACCEPTED= "REQUEST_ACCEPTED",
    REQUEST_ARRIVED="REQUEST_ARRIVED",
    REQUEST_DENIED="REQUEST_DENIED",
    */

    GOTO_REQUEST = "GOTO_REQUEST", //LA TUA RICHIESTA A XXXX HA SUBITO UNA VARIAZIONE



    GOTO_PRODUCT="GOTO_PRODUCT",//QUESTO PRODOTTO E' IN OSSERVAZIONE

    GOTO_SIGNUP_REQUEST="GOTO_SIGNUP_REQUEST", // L'UTENTE XXXX HA RICHIESTO DI ISCRIVERSI
    GOTO_AGENCY="GOTO_AGENCY" //  XXXX HA INSERITO UN NUOVO ANNUNCIO

}